### ISSUE TITLE
Use of uninitialized value in numeric eq (==) at FLT3_ITD_ext.pl line 3100.

### ISSUE THREAD

**Issue by CodingFox25** [ht50/FLT3_ITD_ext#4]
My starting command:
perl FLT3_ITD_ext.pl -f1 /gpfs/data/HX37B_R1.fastq.gz -f2 /gpfs/data/HX37B_R2.fastq.gz -o /gpfs/data/ -g hg38

Samtools version 1.9
Bedtools version 2.26.0
bwa version 0.7.15

I encounter the error in the title after the main perl scrip runs the following command.
bwa mem -M -O 6 -T 20 /gpfs/data/HX37B_FLT3_candidate_ITD_18 /gpfs/data/HX37B_FLT3.nowt.R1.fastq /gpfs/data/HX37B_FLT3.nowt.R2.fastq

Line 3100 of the main perl script reads:

`if( $coverageRadius{$cname}[$i] == 0 ) {`

Thoughts on how to resolve this issue?

**Comment by ht50** [comment]
The coverageRadius and coverageDets are reporting metrics and not strictly necessary, although something is clearly wrong. So one easy thing to try is disabling that code (the for-loop from lines 3098 to 3113, i.e. comment out, delete, or embed in an if(0) statement).   If that succeeds, the concern would still be if the results are okay (you could post the summary or vcf file here if it's not sensitive info).

The other easy thing to try is running the perl script on your bam files, which should result in a lot less candidates since the script evaluates only the FLT3 aligned reads.  If you're concerned about losing reads in the unmapped, you can add the command line argument "-t loose".  In that case, you could first run it in default mode ("-t targeted") and then run "-t loose" to  confirm whether there is a difference.  It's usually unnecessary to run the "loose" mode if the bam was from a local aligner.

I would recommend running directly on the bams if possible.

Otherwise, it would be nice to troubleshoot this.  The most efficient way would be to work directly with the fastqs causing the problem.  I would have to think a bit more about other ways.

**Comment by CodingFox25** [comment]
Commenting out that section works and allows the script to complete successfully. I tried to initially run the script on hg38 aligned bam files but this resulted in the script completing instantly saying:
`NO ITD CANDIDATE CLUSTERS GENERATED. Exiting...`
even though using the fastq files yields the expected ITD
I used 
perl FLT3_ITD_ext.pl --bam /gpfs/data/HX37B_sorted.bam -o /gpfs/data/ -g hg38

**Comment by ht50** [comment]
Hmm...  is your bam sorted by readnames?  The script requires the bam to be sorted by genomic coordinate since it uses samtools to extract the FLT3 locus (sorry, I should add this to the description).  If so, could you try with a coordinate-sorted bam?  It should run significantly faster and generate less candidates to process.  The default -t arg ("targeted") is usually sufficient (definitely if your original pipeline used a local aligner like bwa-mem to generate the bam).  Otherwise, the -t "loose" option can sometimes rescue a few reads from the unmapped; it typically has minimal effect on AR, although I've seen a few problem cases that used older aligners on amplicon assays. 

If that's not the problem, there's a couple other troubleshooting ideas we could try.  Another assumption is that the bam file has either SN:13 or SN:chr13 tags.

**Comment by ht50** [comment]
Hi, another user also had problems with hg38, and traced it to a bug related to alt chr13 contigs.  I just committed their bugfix.  Please give it a try again if you can.  I will close the issue, but feel free to re-open if problems persist.
